// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PostgresEF;

#nullable disable

namespace PostgresEF.Migrations
{
    [DbContext(typeof(PostgresContext))]
    [Migration("20220830095051_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PostgresEF.WowAuction", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AuctionId")
                        .HasColumnType("integer");

                    b.Property<long?>("Buyout")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FirstSeenTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastSeenTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PartitionKey")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<bool>("ShortTimeLeftSeen")
                        .HasColumnType("boolean");

                    b.Property<bool>("Sold")
                        .HasColumnType("boolean");

                    b.Property<long>("UnitPrice")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("WowAuctions");
                });

            modelBuilder.Entity("PostgresEF.WowItem", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BonusList")
                        .HasColumnType("text");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("PetBreedId")
                        .HasColumnType("integer");

                    b.Property<int?>("PetLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("PetQualityId")
                        .HasColumnType("integer");

                    b.Property<int?>("PetSpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WowItems");
                });
#pragma warning restore 612, 618
        }
    }
}
